version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data

networks:
  backend:

volumes:
  db: