version: '3'

services:
    express-redis:
        build: .
        depends_on:
            - redis
        ports:
            - "3000:3000"
        restart: always
        volumes:
            - .:/app
    redis:
        restart: always
        volumes: "redis-data:/data"

volumes:
    redis-data: