version: "3"

services:
    node-dev:
        build: .
        environment:
            - NODE_PORT=3000
        ports:
            - "3000:3000"
        restart: always
        networks:
            - internal
        volumes:
            - ".:/app"
networks:
    internal: