apiVersion: v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-03-02T19:45:58Z"
  generation: 1
  labels:
    app: tslhostname
  name: tslhostname
  namespace: default
  resourceVersion: "6572"
  uid: d1b97ee2-f59f-4d19-a926-1982896d6c10
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tslhostname
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tslhostname
    spec:
      containers:
      - image: mnummeli/tslhostname:0.0.1
        imagePullPolicy: IfNotPresent
        name: tslhostname
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-03-02T19:46:02Z"
    lastUpdateTime: "2023-03-02T19:46:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-02T19:45:58Z"
    lastUpdateTime: "2023-03-02T19:46:02Z"
    message: ReplicaSet "tslhostname-6db7d6bb5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
