apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-02T19:49:35Z"
  labels:
    app: tslhostname
  name: tslhostname
  namespace: default
  resourceVersion: "6724"
  uid: 7d5269da-8231-4bbb-a994-a8187a5a7d69
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.65.56
  clusterIPs:
  - 10.99.65.56
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32451
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tslhostname
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
